name: Documentation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          npm ci
          npm run docs
      - name: Deploy to documentation folder
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_branch: docs
          src_path: /.
          dst_path: /parsnip-ts/
          dst_owner: MCluck90
          dst_repo_name: mcluck90.github.io
          clean: true
